repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bunx prettier --write
        language: system
        files: \.ts$
      - id: rumdl
        name: rumdl
        entry: bunx rumdl check
        language: system
        files: \.md$
