/** The codes every error this server raises carries. */

export enum ErrorCode {
  INVALID_ARGUMENT = "INVALID_ARGUMENT",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_HELD_BY_OTHER_SERVER = "SESSION_HELD_BY_OTHER_SERVER",
  SESSION_BUSY = "SESSION_BUSY",
  SESSION_NOT_RUNNING = "SESSION_NOT_RUNNING",
  REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
  TIMEOUT = "TIMEOUT",
  CANCELLED = "CANCELLED",
  APP_SERVER_START_FAILED = "APP_SERVER_START_FAILED",
  THREAD_FORK_RESUME_FAILED = "THREAD_FORK_RESUME_FAILED",
  PROTOCOL_PARSE_ERROR = "PROTOCOL_PARSE_ERROR",
  WRITE_QUEUE_DROPPED = "WRITE_QUEUE_DROPPED",
  INTERNAL = "INTERNAL",
}
